### ISSUE TITLE
Not an issue but a potential resolution

### ISSUE THREAD

**Issue by Z0ndaa** [baroka/idrive#5]
Hi mate,

First of all I just wanted to thank you for creating this container. I was able to offload much of my Unraid data to idrive because of it!

The one thing that does bug me of course is the cron not persisting on container launch.
I decided to search the internet for other idrive containers and did stumble across one where the creator has figured out this issue but they have since stopped working on releasing new builds.

https://hub.docker.com/r/taverty/idrive/ 

They gave a few instructions on an unraid forum for implementation:

_
> Make sure Idrive is Running when asked
> Then Open Terminal:
> 
> Note: copy&paste code below in terminal then hit Enter after each:
> 
> 7- To create an empty idrivecrontab.json file in the IDrive container
> touch /mnt/user/appdata/idrive/etc/idrivecrontab.json
> 
> 8- in the same Terminal in IDrive Container:
> docker exec -it idrive /bin/bash
> 
> 9- copy and paste then hit enter:
> ./account_setting.pl
> 
> No GUI just Follow prompts from the script and enter your info

_ 

I just thought I'd reach out and maybe assist you with solving your issue. 

I have tried out this container and following the instructions above, I can confirm that dashboard access automatically enables on container reboot. 

Thanks for everything and good luck.

**Comment by baroka** [comment]
Hi,
But the problem is automatize the script account_settings.pl for running on container startup. 
When you run it, prompts for user and other data. I have no luck trying to automatically fill it with expect command.

**Comment by c0f** [comment]
Hi, thank you for creating these files.

There are a few configuration steps that account_settings.pl performs that can't be done before the container is created and won't persist across container restarts without some changes.

account_settings.pl:

1) Creates a file called /etc/idrivecrontab.json
2) Detects the init system in use and, in our case, creates a init script called idrivecron and installs it to /etc/init.d
3) Creates a symbolic link called /etc/idrivecron.pl to /work/IDriveForLinux/scripts/cron.pl
4) Downloads dependencies to /work/IDriveForLinux/scripts/Idrivelib/dependencies
5) Creates a number of user-specific files under /work/IDriveForLinux/scripts/idriveIt
6) Creates a file called /work/IDriveForLinux/scripts/freshInstall
7) Creates a file called /work/IDriveForLinux/scripts/.serviceLocation containing the response to "Enter your service path". If you just press enter at the first question .serviceLocation will contain /work/IDriveForLinux/idriveIt

We need to make all of these persist across container restarts to avoid the need to login every time.

So this is what I did to make this work:

docker-compose.yml
```
version: "3.9"
services:
  idrive:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idrive
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      # Any folder in the container can be backed-up using IDrive. Add one or more mappings here to folders on the host
      - /myfolder:/home/backup:ro
      # idriveIt is populated by account_settings.pl
      - ./idriveIt:/work/IDriveForLinux/idriveIt
      # Use these two commands to create empty files that will be populated by account_settings.pl
      #  mkdir ./etc ./scripts
      #  touch ./etc/idrivecrontab.json ./etc/idrivecron ./scripts/freshInstall ./scripts/serviceLocation
      # These files are required to avoid the need to run account_settings.pl when the container is restarted
      - ./etc/idrivecrontab.json:/etc/idrivecrontab.json
      - ./etc/idrivecron:/etc/init.d/idrivecron
      - ./dependencies:/work/IDriveForLinux/scripts/Idrivelib/dependencies
      - ./scripts/freshInstall:/work/IDriveForLinux/scripts/freshInstall
      - ./scripts/serviceLocation:/work/IDriveForLinux/scripts/.serviceLocation
    restart: unless-stopped
```

entrypoint.sh
```
#!/bin/sh
# Entrypoint for idrive

# This command will fail until account_settings.pl is run
echo "Creating symbolic link /etc/idrivecron.pl"
ln -s /work/IDriveForLinux/scripts/cron.pl /etc/idrivecron.pl

# This command will fail until account_settings.pl is run
echo "Starting idrivecron service"
update-rc.d idrivecron defaults
update-rc.d idrivecron enable
service idrivecron start

# Keep container up
tail -f /dev/null
```

I'm not sure that the update-rc.d lines in entrypoint.sh are required.

With these changes the following proceses should be running across container restarts (view with 'pgrep -af IDrive'):

IDrive:CRON
IDrive:service-watcher
/work/IDriveForLinux/scripts/Idrivelib/dependencies/python/dashboard start

You can check the login status with:

docker exec -it idrive bash
./login.pl

I even rebuilt my container (docker-compose build --no-cache) and it maintained my login to IDrive.

I hope this helps.
